import type { ThreadDB } from "../db/threads.js";
import type { QueueProcessor } from "../../queue/processor.js";
import type { QueueDB } from "../../queue/db.js";
import type { ProposalStore } from "../../proposals/store.js";
import type { TaskStore } from "../../tasks/store.js";
import type { AgentRegistry } from "../../agents/registry.js";
import type { TraceStore } from "../../memory/traces.js";
import type { KnowledgeStore } from "../../memory/knowledge.js";
import type { CompiledKnowledgeStore } from "../../memory/compiled-knowledge.js";
import type { EmbeddingProvider } from "../../memory/embeddings.js";
import type { MemoryStore } from "../../memory/store.js";
import type { Scheduler } from "../../scheduler/index.js";
import type { AuditLog } from "../../utils/audit.js";
import type { NyxHiveConfig } from "../../types.js";
import type { GraphMemory } from "../../memory/graph.js";
import type { ProceduralSkillDraftStore } from "../../memory/procedural-skills.js";
import type { ProviderRouter } from "../../providers/router.js";
import type { CrawlIngestBridge, CrawlService, CrawlSourceStore } from "../../crawl/index.js";
import type { ConnectionManager } from "./connection.js";
import type { DeviceStore } from "./auth.js";
import type { MethodRouter } from "./router.js";
import type { DelegationRunStore } from "../../runs/store.js";

export interface HandlerDeps {
  threadDb?: ThreadDB;
  processor: QueueProcessor;
  queue: QueueDB;
  proposalStore?: ProposalStore;
  taskStore?: TaskStore;
  registry?: AgentRegistry;
  traces?: TraceStore;
  knowledge?: KnowledgeStore;
  compiledKnowledge?: CompiledKnowledgeStore;
  embedder?: EmbeddingProvider;
  memory?: MemoryStore;
  scheduler?: Scheduler;
  connections: ConnectionManager;
  devices: DeviceStore;
  audit?: AuditLog;
  config: NyxHiveConfig;
  configPath: string;
  graphMemory?: GraphMemory;
  proceduralSkills?: ProceduralSkillDraftStore;
  router?: ProviderRouter;
  crawlService?: CrawlService;
  crawlSources?: CrawlSourceStore;
  crawlIngest?: CrawlIngestBridge;
  startTime?: number;
  wsRouter?: MethodRouter;
  runs?: DelegationRunStore;
}
